name: Docker Image Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
    tags:
      - "v*.*"

jobs:
  build:
    if: github.repository == 'adoom2017/vaultwarden-tools'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "ref=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=snapshot" >> $GITHUB_OUTPUT
            echo "ref=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
          echo $GITHUB_REF
          echo "docker_platforms=linux/amd64" >> $GITHUB_OUTPUT
          echo "docker_image=${{ secrets.DOCKER_USERNAME }}/vaultwarden-tools" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        run: |
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
          --output "type=image,push=true" \
          --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
          --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
          --build-arg REF=${{ steps.prepare.outputs.ref }} \
          --file Dockerfile .
